'use strict';
const $=id=>document.getElementById(id);let current=items[15],arc=arcs[0],bond='Lovers',detail=details[0],turn=turns[0],timer;
const pick=(a,old)=>{const pool=a.filter(x=>x!==old);return (pool.length?pool:a)[Math.floor(Math.random()*(pool.length||a.length))]};
Object.keys(groups).forEach(c=>$('category').add(new Option(c,c)));bonds.forEach(b=>$('bond').add(new Option(b,b)));$('count').textContent=`${items.length} objects to begin with`;
function render(){ $('collection').textContent=current.category;$('number').textContent=`OBJECT ${String(items.indexOf(current)+1).padStart(3,'0')} / ${items.length}`;$('object').textContent=current.name;$('sensory').textContent=current.detail;$('tags').replaceChildren(...current.tags.map(t=>{const el=document.createElement('span');el.textContent=t;return el}));$('arcTitle').textContent=arc[0];$('interpretation').textContent=arc[4];$('bondline').textContent=bond;$('question').textContent=bondPrompts[bond];$('association').textContent=`${current.tags[0]} ↔ ${current.tags[1]}`;['first','second','third'].forEach((id,i)=>$(id).textContent=arc[i+1]);$('craft').textContent=arc[5];$('detail').textContent=detail;$('turn').textContent=turn;$('objectRoll').disabled=$('lock').checked;}
function rollObject(){if(!$('lock').checked){const pool=items.filter(x=>$('category').value==='All collections'||x.category===$('category').value);current=pick(pool,current)}render()}
function rollMeaning(){arc=pick(arcs,arc);bond=$('bond').value==='Any relationship'?pick(bonds.slice(1),bond):$('bond').value;render()}
function rollAll(){rollObject();rollMeaning();detail=pick(details,detail);turn=pick(turns,turn);render();announce(`Picked ${current.name}`)}
function announce(t){$('status').textContent=t;clearTimeout(timer);timer=setTimeout(()=>$('status').textContent='',2300)}
$('roll').onclick=rollAll;$('objectRoll').onclick=()=>{rollObject();announce(`Picked ${current.name}`)};$('meaningRoll').onclick=rollMeaning;$('lock').onchange=render;$('category').onchange=()=>{if($('lock').checked)announce('Object kept. Uncheck Keep this object to use the new collection.');else rollObject()};$('bond').onchange=()=>{bond=$('bond').value==='Any relationship'?pick(bonds.slice(1),bond):$('bond').value;render()};$('detailRoll').onclick=()=>{detail=pick(details,detail);render()};$('turnRoll').onclick=()=>{turn=pick(turns,turn);render()};
function setMode(simple){document.body.classList.toggle('simple',simple);$('simple').setAttribute('aria-pressed',String(simple));$('explore').setAttribute('aria-pressed',String(!simple));try{localStorage.setItem('keepsake-mode',simple?'simple':'explore')}catch{}}
$('simple').onclick=()=>setMode(true);$('explore').onclick=()=>setMode(false);
function promptText(){let text=`${current.name} (${current.category})\n${current.detail}\nPossible associations: ${current.tags.join(' / ')}`;if(!document.body.classList.contains('simple'))text+=`\n\n${bond}: ${bondPrompts[bond]}\n${arc[0]} — ${arc[4]}\n\n1. ${arc[1]}\n2. ${arc[2]}\n3. ${arc[3]}\n\nOn the page: ${arc[5]}\nPersonal detail: ${detail}\nComplication: ${turn}`;return text}
$('copy').onclick=async()=>{const text=promptText();try{await navigator.clipboard.writeText(text);announce('Prompt copied')}catch{const field=document.createElement('textarea');field.value=text;field.style.position='fixed';field.style.top='0';document.body.append(field);field.select();const ok=document.execCommand('copy');field.remove();announce(ok?'Prompt copied':'Copy unavailable in this browser. Select the text on the page.')}};
let installEvent;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e});$('install').onclick=async()=>{if(installEvent){await installEvent.prompt();installEvent=null}else $('installDialog').showModal()};
try{setMode(localStorage.getItem('keepsake-mode')==='simple')}catch{}render();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'pick_keepsake',title:'Pick a keepsake',description:'Roll the visible object and relationship prompts, respecting the Keep this object checkbox.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');rollAll();return {object:current.name,prompt:promptText()}}})).catch(()=>{})}catch{}}
