const groups = {
'Everyday': [
['Chipped mug','A crescent of glaze is missing where a thumb rests.','routine|absence'],['Spare key','Its teeth have rubbed a pale shape into a pocket.','access|exclusion'],['Bus ticket','The crease runs through the destination.','departure|return'],['Bent spoon','It rocks on a flat table.','care|improvisation'],['Pencil stub','Teeth marks crowd the last inch of paint.','learning|persistence'],['Matchbox','One match rattles inside.','possibility|finality'],['Shopping list','One item is written in a second hand.','domesticity|attention'],['Bottle cap','The crimped edge has been flattened.','play|scarcity'],['Lunch tin','Something sweet lingers beneath the metal smell.','provision|shame'],['Umbrella','One rib lifts the fabric out of line.','shelter|distance'],['House slipper','The heel is worn down on one side.','home|waiting'],['Soap sliver','An old fragrance returns when it gets wet.','intimacy|erosion'],['Rubber band','It has gone pale where it was stretched.','holding|restriction'],['Receipt','The ink is fading faster than the fold.','proof|forgetting'],['Tea strainer','The mesh has darkened along its seam.','ritual|patience']],
'Wearable': [
['Hand-carved hairpin','A shallow knife slip interrupts the polished grain.','devotion|possession'],['Loose button','A tiny cross of thread remains in its holes.','repair|separation'],['Wool scarf','A different yarn closes the hole near one end.','warmth|dependence'],['Single earring','Its clasp catches when it closes.','pairing|imbalance'],['Leather glove','The fingers keep the curve of a vanished hand.','protection|touch'],['Ribbon','Its color survives best inside the knot.','attachment|restraint'],['Pocket watch','The case is warm before the hands start moving.','inheritance|delay'],['Uniform patch','The stitch holes outline a former home.','belonging|obedience'],['Beaded bracelet','One bead is smoother than the others.','counting|memory'],['Bootlace','One end has been stiffened with wax.','readiness|entanglement'],['Broken clasp','It looks closed until it bears weight.','trust|appearance'],['Apron','A small handprint interrupts the flour stains.','service|authority'],['Spectacle case','The lining has worn through at the hinge.','perception|vulnerability'],['Cheap ring','The finish has left a green band on skin.','promise|pretending'],['Child-sized mitten','A name is sewn inside in oversized letters.','growth|loss']],
'Paper & records': [
['Unsent letter','The greeting has been crossed out twice.','confession|silence'],['Folded map','A route has been traced hard enough to dent it.','guidance|control'],['Photograph','One face is blurred by a thumbprint.','witness|revision'],['Recipe card','A greasy fingerprint covers the cooking time.','inheritance|adaptation'],['Library card','The signature belongs to an earlier version of its owner.','curiosity|permission'],['Pressed flower bookmark','A petal has stained the page it touched.','preservation|fragility'],['Music score','An extra breath is marked in pencil.','harmony|difference'],['Childhood drawing','The smallest figure has the largest hands.','perception|misunderstanding'],['Train timetable','An obsolete departure is circled.','waiting|missed chances'],['Postcard','The message ends halfway through a sentence.','distance|interruption'],['Certificate','The seal is crisp; the name has been corrected.','recognition|erasure'],['Diary page','The torn edge still fits somewhere.','privacy|evidence'],['Cinema ticket','Two seats are printed on one faded strip.','shared time|nostalgia'],['Envelope of seeds','The planting instructions are in unfamiliar handwriting.','future|trust'],['Annotated book','Two readers argue in the margins.','companionship|disagreement']],
'Nature': [
['River stone','One side holds warmth longer than the other.','steadiness|change'],['Seashell','Sand still sifts from its spiral.','distance|home'],['Acorn','The cap comes away with a tiny click.','potential|inheritance'],['Shed feather','A bent barb will no longer lie flat.','freedom|trace'],['Driftwood','Salt has raised the grain into ridges.','survival|displacement'],['Dried orange peel','Its scent wakes when the edge is bent.','abundance|remembrance'],['Sea glass','A sharp origin has become a soft edge.','transformation|erosion'],['Pinecone','Its scales open in a warmer room.','readiness|reserve'],['Root cutting','A pale new root curls against the jar.','continuity|dependence'],['Fossil','A vanished creature leaves a precise hollow.','duration|absence'],['Smooth bone','Its surface has become almost ivory-white.','mortality|survival'],['Dried leaf','The veins outlast the green.','season|structure'],['Jar of soil','A fine line marks where it settled.','belonging|exile'],['Salt crystal','Damp air rounds its corners.','preservation|dissolution'],['Fruit pit','A little pulp remains in the groove.','aftermath|renewal']],
'Tools & craft': [
['Sewing needle','Its eye is easier to feel than to see.','mending|hurt'],['Wooden thimble','The rim carries a shallow split.','protection|labor'],['Carving knife','The handle is polished only where fingers meet it.','making|danger'],['Compass','The needle hesitates before settling.','guidance|doubt'],['Paintbrush','An old color survives near the ferrule.','expression|residue'],['Measuring tape','The first inch has almost disappeared.','precision|judgment'],['Tuning fork','Its hum travels through a tabletop.','attunement|discord'],['Fishing float','The paint is brightest below the waterline.','patience|hope'],['Spool of thread','A second color is knotted underneath.','continuity|repair'],['Whetstone','A groove follows years of the same motion.','practice|violence'],['Clay stamp','Dried clay fills the smallest line.','authorship|ownership'],['Pocket screwdriver','The tip is rounded from jobs it barely managed.','usefulness|limits'],['Garden trowel','Earth remains under the handle lip.','nurture|burial'],['Whistle','A dent changes the note.','summons|warning'],['Work notebook','The same calculation appears on three pages.','discipline|obsession']],
'Weapons & defense': [
['Practice sword','The grip has been wrapped for smaller hands.','discipline|restraint'],['Arrowhead','One shoulder is chipped.','aim|consequence'],['Empty scabbard','Its lining remembers a shape that is gone.','readiness|renunciation'],['Shield strap','A repair has shortened its reach.','protection|burden'],['Broken spear tip','The break exposes bright metal.','defeat|survival'],['Ceremonial dagger','Its decoration is sharper than its edge.','status|performance'],['Sling','The pouch is stretched unevenly.','resourcefulness|asymmetry'],['Spent cartridge','Its casing holds a small crescent dent.','aftermath|evidence'],['Sword tassel','One strand has been braided back in.','identity|attachment'],['Blunted knife','The point has been deliberately rounded.','mercy|mistrust'],['Archery glove','Two fingers are darkened by use.','practice|cost'],['Helmet fragment','The inside carries a trace of paint.','survival|vulnerability'],['Torn surrender flag','A knot has become too tight to undo.','mercy|humiliation'],['Protective charm','Repeated touching has worn off the inscription.','faith|uncertainty'],['Blackmail photograph','Its corner has been cut off.','leverage|exposure']],
'Technology': [
['Cracked phone','The fracture passes through a saved face.','connection|interruption'],['Single earbud','The mesh has a tiny dent.','shared listening|isolation'],['USB drive','The label has been peeled off and replaced.','secrecy|inheritance'],['Voice recorder','The play button is smoother than the others.','presence|repetition'],['Dead battery','Its weight promises more than it can give.','potential|depletion'],['Game cartridge','A name is scratched into the plastic.','play|rivalry'],['Access badge','A faded photo sits above an active chip.','permission|identity'],['Old SIM card','Its cut corner looks surprisingly deliberate.','contact|separation'],['Mechanical keycap','The letter has worn away.','habit|expression'],['Charging cable','A colored thread identifies one end.','dependence|care'],['Memory card','It fits inside a folded scrap of paper.','evidence|fragility'],['Robot component','A serial number has been hand-corrected.','personhood|replacement'],['Wrist tracker','Its strap still holds an old adjustment.','care|surveillance'],['Camera lens cap','A tiny scratch crosses the logo.','attention|neglect'],['Music player','One song begins louder than the rest.','association|replay']],
'Fantastical': [
['Memory pearl','It warms when someone misremembers its owner.','memory|revision'],['Shadow needle','Its shadow points toward a different light.','repair|concealment'],['Name vial','A syllable mists the glass when breathed upon.','identity|possession'],['Weather coin','One face is always wet.','change|bargain'],['Dream key','Its teeth rearrange after sleep.','access|uncertainty'],['Soul lantern wick','It glows without consuming itself.','presence|captivity'],['Returning button','It appears on a different coat each dawn.','attachment|escape'],['Borrowed heartbeat stone','Its rhythm falters near its maker.','intimacy|dependence'],['Truth-stained ribbon','Its color changes only after the conversation ends.','honesty|delay'],['Unmelting snowflake','The container is colder than its contents.','preservation|impossibility'],['Letter from tomorrow','The date changes; the salutation never does.','fate|recognition'],['Echo bell','It repeats the last word its giver spoke.','absence|unfinished business'],['Promise thread','It tightens when two people describe the promise differently.','commitment|interpretation'],['Door seed','It sprouts into an entrance without a destination.','possibility|exile'],['Glass tear','It becomes opaque when its story is told falsely.','grief|ownership']]
};
const items=Object.entries(groups).flatMap(([category,rows])=>rows.map(([name,detail,tags])=>({name,detail,tags:tags.split('|'),category})));
const bonds=['Any relationship','Lovers','Friends','Siblings','Parent & child','Mentor & student','Rivals','Strangers','Former allies'];
const bondPrompts={
'Lovers':'Which ordinary preference does one remember that nobody else notices?',
'Friends':'What shared joke makes the object unintelligible to outsiders?',
'Siblings':'Who remembers its origin differently—and who has been called its rightful owner?',
'Parent & child':'When does a token of care begin to feel like a claim on the child?',
'Mentor & student':'What happens when the student changes the object or outgrows its original use?',
'Rivals':'Why would one keep evidence that the other once helped them?',
'Strangers':'What small act makes returning this object worth finding someone again?',
'Former allies':'Which part of their former trust survives in the way they handle it?'};
const arcs=[
['A practical kindness','One person notices a small difficulty and offers the object without ceremony.','Later, the recipient reaches for it before asking anyone for help.','They offer it to someone else, repeating—or correcting—the original kindness.','Care becomes a learned action.','Let the first use solve a real problem before it carries symbolism.'],
['The unfinished loan','Someone lends it with a casual “bring it back.”','An opportunity to return it comes and goes; keeping it extends the connection.','Returning it can close the relationship, or finally make room for a chosen reunion.','An obligation becomes an excuse to stay connected.','Repeat the return question with a different answer.'],
['Unequal meaning','The giver treats it as disposable; the recipient keeps it carefully.','The giver discovers how much has been invested in that small gesture.','They must decide whether to acknowledge that meaning or withdraw from it.','Gratitude and expectation diverge.','Show different handling: tossed onto a table versus wrapped before travel.'],
['Repair as an answer','It is damaged during a disagreement or separation.','One character repairs it without asking whether the other still wants it.','The other uses it, rejects it, or alters the repair.','Mending may offer care, or presume forgiveness.','Leave a visible seam; repair needn’t erase what happened.'],
['The inherited habit','It arrives with a rule about how its previous owner used it.','The new keeper follows the rule even when it is inconvenient.','They change the use while preserving something of the person.','Loyalty becomes permission to grow.','Give the old habit a specific bodily action.'],
['A claim disguised as a gift','The giver insists that accepting it means belonging to them.','The recipient must display it to keep the giver satisfied.','Keeping, returning, or repurposing it becomes a choice about autonomy.','Affection turns into ownership.','Let the terms of the gift emerge in behavior.'],
['The false provenance','A cherished story explains where it came from.','A physical detail contradicts that story.','Its keeper chooses whether its lived meaning survives the lie.','Origin and earned meaning separate.','Plant the contradictory detail before explaining it.'],
['Recognition without a face','A distinctive handling habit is established when both people are together.','The object surfaces elsewhere, bearing evidence of the same habit.','Someone recognizes the person through the gesture or trace.','A small habit carries identity across absence.','Make the identifying trace plausible and specific.'],
['Refused, then accepted','An offer is rejected because accepting help feels costly.','The same need returns when the giver is absent or unavailable.','Accepting the object now acknowledges something the character once denied.','Pride shifts toward trust.','Reuse the original gesture with a changed response.'],
['A substitute that fails','One person replaces the lost object with something finer.','The replacement lacks the mark or inconvenience that mattered.','They learn what cannot be purchased—or create a new shared history.','Value separates from price.','Make the missing imperfection carry a remembered action.'],
['A shared custody','Two people agree to exchange it at a regular interval.','One exchange is missed, delayed, or carried out by a third person.','The next handoff reveals whether the ritual still binds them.','Routine becomes a measure of commitment.','Vary one element of a familiar exchange.'],
['Released on purpose','Someone protects it long after its practical use has ended.','Keeping it begins to obstruct a present need or relationship.','They give it away, use it up, or let it change.','Letting go can complete an attachment.','Make release a visible action, without requiring an explanatory speech.']
];
const details=['A hidden mark only one person would recognize.','Wear that reveals how it was held, carried, or used.','A repair made with materials the owner would never choose.','A smell that belongs to its former surroundings.','A missing part that the keeper refuses to replace.','A stain with an innocent explanation and a private one.','A date that means something different to each person.','An awkward size or weight that makes keeping it inconvenient.','A concealed message that was never meant to be found.','A small sound that announces its presence before it is seen.','A mistaken name that nobody has corrected.','A change in texture that can be noticed in darkness.'];
const turns=['The person who gave it denies remembering the gift.','Someone repairs the feature its keeper valued most.','A stranger recognizes it for an entirely different reason.','The keeper discovers a second, apparently identical object.','It turns up in the possession of someone considered an enemy.','Someone uses it for its ordinary purpose during a solemn moment.','The person who wanted it finally has a chance to refuse it.','Its usefulness matters more than its history for one urgent scene.','A child invents a new meaning for it.','The story attached to it is true, but belongs to a different person.','It survives the relationship and enters another.','The keeper realizes they have forgotten one detail they thought permanent.'];
