const groups = {
'Everyday': [
['Chipped mug','A crescent of glaze is missing where a thumb rests.','routine|absence'],['Spare key','Its teeth have rubbed a pale shape into a pocket.','access|exclusion'],['Bus ticket','The crease runs through the destination.','departure|return'],['Bent spoon','It rocks on a flat table.','care|improvisation'],['Pencil stub','Teeth marks crowd the last inch of paint.','learning|persistence'],['Matchbox','One match rattles inside.','possibility|finality'],['Shopping list','One item is written in a second hand.','domesticity|attention'],['Bottle cap','The crimped edge has been flattened.','play|scarcity'],['Lunch tin','Something sweet lingers beneath the metal smell.','provision|shame'],['Umbrella','One rib lifts the fabric out of line.','shelter|distance'],['House slipper','The heel is worn down on one side.','home|waiting'],['Soap sliver','An old fragrance returns when it gets wet.','intimacy|erosion'],['Rubber band','It has gone pale where it was stretched.','holding|restriction'],['Receipt','The ink is fading faster than the fold.','proof|forgetting'],['Tea strainer','The mesh has darkened along its seam.','ritual|patience'],
["Doorstop", "A stripe of paint marks the door it held open.", "welcome|resistance"],
["Kitchen timer", "The dial sticks just short of the usual setting.", "anticipation|interruption"],
["Cloth napkin", "One corner has been folded more often than the others.", "hospitality|habit"],
["Coin purse", "The lining holds the outline of a coin no longer inside.", "thrift|security"],
["Water bottle", "A shallow dent fits the pad of a thumb.", "sustenance|journey"],
["Clothes peg", "One wooden half has weathered darker than its partner.", "partnership|endurance"],
["Doorbell plate", "A second surname shows beneath the newer lettering.", "arrival|replacement"],
["Scrubbing brush", "The bristles lean away from the hand that used it.", "care|invisible labor"],
["Egg cup", "A hairline crack divides the painted bird.", "comfort|fragility"],
["Candle end", "A loop of thread is trapped in the cooled wax.", "vigil|exhaustion"],
["Coaster", "A water ring crosses the printed coastline.", "hospitality|boundaries"],
["Hot-water bottle", "The knitted cover is loose around the neck.", "comfort|aging"],
["Tea tin", "The lid still snaps shut despite the dented rim.", "ritual|concealment"],
["Bread bag", "Flour has settled deep into the cloth seams.", "provision|economy"],
["Fridge magnet", "A shopping list has faded around its outline.", "attachment|overlooked presence"]],
'Wearable': [
['Hand-carved hairpin','A shallow knife slip interrupts the polished grain.','devotion|possession'],['Loose button','A tiny cross of thread remains in its holes.','repair|separation'],['Wool scarf','A different yarn closes the hole near one end.','warmth|dependence'],['Single earring','Its clasp catches when it closes.','pairing|imbalance'],['Leather glove','The fingers keep the curve of a vanished hand.','protection|touch'],['Ribbon','Its color survives best inside the knot.','attachment|restraint'],['Pocket watch','The case is warm before the hands start moving.','inheritance|delay'],['Uniform patch','The stitch holes outline a former home.','belonging|obedience'],['Beaded bracelet','One bead is smoother than the others.','counting|memory'],['Bootlace','One end has been stiffened with wax.','readiness|entanglement'],['Broken clasp','It looks closed until it bears weight.','trust|appearance'],['Apron','A small handprint interrupts the flour stains.','service|authority'],['Spectacle case','The lining has worn through at the hinge.','perception|vulnerability'],['Cheap ring','The finish has left a green band on skin.','promise|pretending'],['Child-sized mitten','A name is sewn inside in oversized letters.','growth|loss'],
["Cufflink", "The hinge was replaced with a different metal.", "formality|compromise"],
["Sun hat", "A pale band shows where the ribbon used to sit.", "shelter|vanity"],
["Darning sock", "The heel contains more repair than original wool.", "devotion|frugality"],
["Silk tie", "A small burn disappears inside the knot.", "composure|concealment"],
["Belt buckle", "A scratched initial is visible on the underside.", "identity|constraint"],
["Locket", "A scrap of fabric cushions the empty picture frame.", "intimacy|withholding"],
["Dance shoe", "The sole has been roughened by hand.", "partnership|effort"],
["Wedding veil", "A snag catches the light beside the hem.", "expectation|hesitation"],
["Raincoat", "The cuffs are dry while the pockets smell of rain.", "protection|secrecy"],
["Knitted vest", "The armholes were enlarged with a contrasting yarn.", "growth|accommodation"],
["Enamel brooch", "A fleck of color remains caught in the fastening.", "allegiance|display"],
["Suspenders", "One clip grips harder than the other.", "support|unequal effort"],
["Headband", "The elastic has relaxed to a particular shape.", "habit|belonging"],
["Baby bootie", "The sole has never touched the ground.", "anticipation|tenderness"],
["Festival wristband", "The printed date has washed away before the color.", "shared time|reluctance"]],
'Paper & records': [
['Unsent letter','The greeting has been crossed out twice.','confession|silence'],['Folded map','A route has been traced hard enough to dent it.','guidance|control'],['Photograph','One face is blurred by a thumbprint.','witness|revision'],['Recipe card','A greasy fingerprint covers the cooking time.','inheritance|adaptation'],['Library card','The signature belongs to an earlier version of its owner.','curiosity|permission'],['Pressed flower bookmark','A petal has stained the page it touched.','preservation|fragility'],['Music score','An extra breath is marked in pencil.','harmony|difference'],['Childhood drawing','The smallest figure has the largest hands.','perception|misunderstanding'],['Train timetable','An obsolete departure is circled.','waiting|missed chances'],['Postcard','The message ends halfway through a sentence.','distance|interruption'],['Certificate','The seal is crisp; the name has been corrected.','recognition|erasure'],['Diary page','The torn edge still fits somewhere.','privacy|evidence'],['Cinema ticket','Two seats are printed on one faded strip.','shared time|nostalgia'],['Envelope of seeds','The planting instructions are in unfamiliar handwriting.','future|trust'],['Annotated book','Two readers argue in the margins.','companionship|disagreement'],
["Ration book", "One square was cut out with unusual care.", "scarcity|sacrifice"],
["School report", "A penciled comment softens the printed verdict.", "judgment|advocacy"],
["Telegram", "The fold falls between the name and the news.", "urgency|distance"],
["Sheet of stamps", "A single corner stamp has been left behind.", "departure|hesitation"],
["Menu", "A dish has been circled on the back in lipstick.", "appetite|celebration"],
["Visitor pass", "The departure time was never filled in.", "permission|unfinished business"],
["Pet adoption form", "The original name is still legible under the new one.", "care|new beginnings"],
["Paper crown", "The tape repair pulls at a lock of caught hair.", "play|authority"],
["Wedding invitation", "The address is correct but the surname is old.", "recognition|estrangement"],
["Carbon copy", "A sentence is darker where the writer pressed harder.", "evidence|insistence"],
["Family tree", "A branch continues beyond the edge on taped paper.", "kinship|omission"],
["Pay envelope", "A column of tiny sums fills the inside flap.", "labor|obligation"],
["Prayer card", "The printed border has worn away beneath a thumb.", "faith|reassurance"],
["Lost-property tag", "The description names everything except the owner.", "recovery|anonymity"],
["Rehearsal schedule", "Two names share the same penciled correction.", "coordination|ambition"]],
'Nature': [
['River stone','One side holds warmth longer than the other.','steadiness|change'],['Seashell','Sand still sifts from its spiral.','distance|home'],['Acorn','The cap comes away with a tiny click.','potential|inheritance'],['Shed feather','A bent barb will no longer lie flat.','freedom|trace'],['Driftwood','Salt has raised the grain into ridges.','survival|displacement'],['Dried orange peel','Its scent wakes when the edge is bent.','abundance|remembrance'],['Sea glass','A sharp origin has become a soft edge.','transformation|erosion'],['Pinecone','Its scales open in a warmer room.','readiness|reserve'],['Root cutting','A pale new root curls against the jar.','continuity|dependence'],['Fossil','A vanished creature leaves a precise hollow.','duration|absence'],['Smooth bone','Its surface has become almost ivory-white.','mortality|survival'],['Dried leaf','The veins outlast the green.','season|structure'],['Jar of soil','A fine line marks where it settled.','belonging|exile'],['Salt crystal','Damp air rounds its corners.','preservation|dissolution'],['Fruit pit','A little pulp remains in the groove.','aftermath|renewal'],
["Walnut shell", "The two halves fit together only one way.", "separation|wholeness"],
["Horseshoe crab molt", "Light passes through the empty joints.", "growth|abandonment"],
["Piece of bark", "A strand of pale lichen crosses a dark fissure.", "shelter|age"],
["Dandelion seed head", "Three seeds cling to the sheltered side.", "departure|reluctance"],
["Beeswax lump", "The warmth of a hand brings back its scent.", "cooperation|industry"],
["Quartz pebble", "A cloudy seam interrupts the clear tip.", "clarity|imperfection"],
["Snail shell", "The lip has broken into a tiny staircase.", "shelter|vulnerability"],
["Cattail fluff", "A few strands cling to the inside of the envelope.", "dispersal|attachment"],
["Dried mushroom", "The gills crumble before the stem bends.", "sustenance|uncertainty"],
["Beach sand", "A dark layer settles beneath the pale grains.", "place|multiplicity"],
["Sprig of rosemary", "The smallest leaves remain green at the stem.", "remembrance|hospitality"],
["Antler tine", "The broken base is rough against the polished tip.", "renewal|contest"],
["Lotus seedpod", "One seed still knocks inside its chamber.", "possibility|emptiness"],
["Cicada shell", "The split down its back has caught a blade of grass.", "emergence|trace"],
["Petrified wood", "The grain looks soft until a finger touches it.", "duration|transformation"]],
'Tools & craft': [
['Sewing needle','Its eye is easier to feel than to see.','mending|hurt'],['Wooden thimble','The rim carries a shallow split.','protection|labor'],['Carving knife','The handle is polished only where fingers meet it.','making|danger'],['Compass','The needle hesitates before settling.','guidance|doubt'],['Paintbrush','An old color survives near the ferrule.','expression|residue'],['Measuring tape','The first inch has almost disappeared.','precision|judgment'],['Tuning fork','Its hum travels through a tabletop.','attunement|discord'],['Fishing float','The paint is brightest below the waterline.','patience|hope'],['Spool of thread','A second color is knotted underneath.','continuity|repair'],['Whetstone','A groove follows years of the same motion.','practice|violence'],['Clay stamp','Dried clay fills the smallest line.','authorship|ownership'],['Pocket screwdriver','The tip is rounded from jobs it barely managed.','usefulness|limits'],['Garden trowel','Earth remains under the handle lip.','nurture|burial'],['Whistle','A dent changes the note.','summons|warning'],['Work notebook','The same calculation appears on three pages.','discipline|obsession'],
["Crochet hook", "A thumb has polished one flat patch on the handle.", "patience|creation"],
["Spirit level", "A smear of plaster obscures one end of the bubble.", "balance|judgment"],
["Leather awl", "The handle bears a ring where it was once bound.", "persistence|hurt"],
["Pottery rib", "Dried slip preserves the ridge of a fingerprint.", "shaping|influence"],
["Tailor’s chalk", "One edge is sharp; the rest has rounded away.", "intention|impermanence"],
["Printing block", "A reversed letter has been recut by hand.", "expression|correction"],
["Knitting needle", "Its partner has left a groove in the storage sleeve.", "rhythm|companionship"],
["Welding goggles", "A clear crescent survives beneath a soot stain.", "protection|perception"],
["Seed dibber", "Three depth marks were carved at uneven intervals.", "nurture|experience"],
["Plumb bob", "The cord is knotted where it once snapped.", "alignment|trust"],
["Violin rosin", "A narrow track divides the amber surface.", "preparation|expression"],
["Bookbinding folder", "Ink has darkened its tapered end.", "order|preservation"],
["Embroidery hoop", "The inner ring has been wrapped in faded cloth.", "tension|care"],
["Watchmaker’s loupe", "A small chip rests just outside the field of view.", "attention|blindness"],
["Cookie cutter", "One side has bent enough to change the familiar shape.", "tradition|adaptation"]],
'Weapons & defense': [
['Practice sword','The grip has been wrapped for smaller hands.','discipline|restraint'],['Arrowhead','One shoulder is chipped.','aim|consequence'],['Empty scabbard','Its lining remembers a shape that is gone.','readiness|renunciation'],['Shield strap','A repair has shortened its reach.','protection|burden'],['Broken spear tip','The break exposes bright metal.','defeat|survival'],['Ceremonial dagger','Its decoration is sharper than its edge.','status|performance'],['Sling','The pouch is stretched unevenly.','resourcefulness|asymmetry'],['Spent cartridge','Its casing holds a small crescent dent.','aftermath|evidence'],['Sword tassel','One strand has been braided back in.','identity|attachment'],['Blunted knife','The point has been deliberately rounded.','mercy|mistrust'],['Archery glove','Two fingers are darkened by use.','practice|cost'],['Helmet fragment','The inside carries a trace of paint.','survival|vulnerability'],['Torn surrender flag','A knot has become too tight to undo.','mercy|humiliation'],['Protective charm','Repeated touching has worn off the inscription.','faith|uncertainty'],['Blackmail photograph','Its corner has been cut off.','leverage|exposure'],
["Mail link", "A bright solder seam closes the darkened ring.", "interdependence|repair"],
["Bowstring", "The serving is worn where an arrow used to rest.", "tension|discipline"],
["Training shield", "Chalk circles mark where the last blows landed.", "learning|vulnerability"],
["Peace medal", "The ribbon is newer than the tarnished disc.", "reconciliation|display"],
["Signal mirror", "A fingerprint interrupts the reflected flash.", "rescue|exposure"],
["Armistice token", "Two different seals overlap on the soft metal.", "agreement|mistrust"],
["Fencing mask", "A dent sits just above the line of sight.", "restraint|risk"],
["Sword knot", "The loop has been loosened and tightened many times.", "duty|release"],
["Evacuation whistle", "A name is scratched beneath the mouthpiece.", "protection|separation"],
["Shin guard", "The padding has flattened around an old repair.", "endurance|cost"],
["Gate bolt", "Its polished underside contrasts with the rusted top.", "security|exclusion"],
["White armband", "A darker rectangle marks a removed insignia.", "neutrality|history"],
["Practice target", "Several holes have been patched with the same scrap.", "ambition|repetition"],
["Watch bell", "The clapper is tied still with a strip of cloth.", "vigilance|silence"],
["Scabbard fitting", "The worn metal carries the outline of a missing crest.", "loyalty|renunciation"]],
'Technology': [
['Cracked phone','The fracture passes through a saved face.','connection|interruption'],['Single earbud','The mesh has a tiny dent.','shared listening|isolation'],['USB drive','The label has been peeled off and replaced.','secrecy|inheritance'],['Voice recorder','The play button is smoother than the others.','presence|repetition'],['Dead battery','Its weight promises more than it can give.','potential|depletion'],['Game cartridge','A name is scratched into the plastic.','play|rivalry'],['Access badge','A faded photo sits above an active chip.','permission|identity'],['Old SIM card','Its cut corner looks surprisingly deliberate.','contact|separation'],['Mechanical keycap','The letter has worn away.','habit|expression'],['Charging cable','A colored thread identifies one end.','dependence|care'],['Memory card','It fits inside a folded scrap of paper.','evidence|fragility'],['Robot component','A serial number has been hand-corrected.','personhood|replacement'],['Wrist tracker','Its strap still holds an old adjustment.','care|surveillance'],['Camera lens cap','A tiny scratch crosses the logo.','attention|neglect'],['Music player','One song begins louder than the rest.','association|replay'],
["Floppy disk", "The write-protect tab has been taped in place.", "preservation|obsolescence"],
["Pager", "A strip of tape lists a number without a name.", "availability|obligation"],
["Remote control", "One button has been marked with a raised dot.", "accessibility|care"],
["Circuit board", "One hand-soldered joint shines brighter than the others.", "repair|individuality"],
["Cassette adapter", "The cable keeps the bend of a closed glovebox.", "translation|continuity"],
["Electronic key fob", "The rubber has worn through over the unlock button.", "access|habit"],
["Laptop hinge", "A thin strip of tape carries a handwritten arrow.", "support|limits"],
["Digital photo frame", "A reflection crosses the face in the paused image.", "presence|curation"],
["Portable radio", "Two stations have been marked on the dial.", "company|distance"],
["Printer ribbon", "A faint line of letters repeats along its length.", "record|residue"],
["Charging dock", "Dust outlines the device that used to stand there.", "readiness|absence"],
["Trackball", "One side gleams more brightly from repeated touch.", "control|adaptation"],
["Microphone", "The grille holds a caught strand of colored thread.", "voice|exposure"],
["Solar calculator", "The casing is faded except beneath an old label.", "resourcefulness|certainty"],
["Video tape", "The handwritten title has been overwritten three times.", "memory|replacement"]],
'Fantastical': [
['Memory pearl','It warms when someone misremembers its owner.','memory|revision'],['Shadow needle','Its shadow points toward a different light.','repair|concealment'],['Name vial','A syllable mists the glass when breathed upon.','identity|possession'],['Weather coin','One face is always wet.','change|bargain'],['Dream key','Its teeth rearrange after sleep.','access|uncertainty'],['Soul lantern wick','It glows without consuming itself.','presence|captivity'],['Returning button','It appears on a different coat each dawn.','attachment|escape'],['Borrowed heartbeat stone','Its rhythm falters near its maker.','intimacy|dependence'],['Truth-stained ribbon','Its color changes only after the conversation ends.','honesty|delay'],['Unmelting snowflake','The container is colder than its contents.','preservation|impossibility'],['Letter from tomorrow','The date changes; the salutation never does.','fate|recognition'],['Echo bell','It repeats the last word its giver spoke.','absence|unfinished business'],['Promise thread','It tightens when two people describe the promise differently.','commitment|interpretation'],['Door seed','It sprouts into an entrance without a destination.','possibility|exile'],['Glass tear','It becomes opaque when its story is told falsely.','grief|ownership'],
["Compass for lost things", "Its needle trembles near anything willingly given away.", "longing|release"],
["Pocket-sized dusk", "The last light gathers in the crease of its pouch.", "ending|shelter"],
["Apology spool", "Its thread breaks whenever an excuse is spoken.", "accountability|repair"],
["Mirror shard of home", "It reflects a room with one chair always empty.", "belonging|absence"],
["Hush thimble", "A fingertip inside it cannot make a sound.", "tenderness|suppression"],
["Unchosen-path ticket", "The destination appears only after the train has left.", "regret|possibility"],
["Season jar", "A single leaf changes color against the sealed glass.", "patience|control"],
["Borrowed courage pin", "Its point grows cold when its lender is afraid.", "dependence|reciprocity"],
["Forgetful lock", "Each morning it accepts a different familiar key.", "privacy|recognition"],
["Tide marble", "A tiny shoreline moves when its holder changes their mind.", "uncertainty|influence"],
["Moth-wing letter", "Its words settle only when nobody is reading.", "confession|elusiveness"],
["Second-chance match", "Its flame illuminates one thing left unsaid.", "opportunity|finality"],
["Hospitality cup", "It fills only when an unexpected guest is welcomed.", "generosity|boundaries"],
["Witness pebble", "It grows heavier when its keeper omits a detail.", "truth|burden"],
["Farewell comb", "Each stroke loosens a memory without erasing it.", "grief|permission"]]
};
const items=Object.entries(groups).flatMap(([category,rows])=>rows.map(([name,detail,tags])=>({name,detail,tags:tags.split('|'),category})));
const bonds=['Any relationship','Lovers','Friends','Siblings','Parent & child','Mentor & student','Rivals','Strangers','Former allies','Neighbors','Coworkers','Caregiver & recipient','Teacher & parent','Estranged friends','Travel companions','Collaborators','Host & guest'];
const bondPrompts={
'Lovers':'Which ordinary preference does one remember that nobody else notices?',
'Friends':'What shared joke makes the object unintelligible to outsiders?',
'Siblings':'Who remembers its origin differently—and who has been called its rightful owner?',
'Parent & child':'When does a token of care begin to feel like a claim on the child?',
'Mentor & student':'What happens when the student changes the object or outgrows its original use?',
'Rivals':'Why would one keep evidence that the other once helped them?',
'Strangers':'What small act makes returning this object worth finding someone again?',
'Former allies':'Which part of their former trust survives in the way they handle it?',
"Neighbors":"What borrowed object turns living nearby into taking responsibility for one another?",
"Coworkers":"What does passing it between shifts reveal that their job titles conceal?",
"Caregiver & recipient":"How does the person receiving care use it to express a preference or set a boundary?",
"Teacher & parent":"What different versions of the same child do they see in this object?",
"Estranged friends":"Which old permission does one assume still holds when the object reappears?",
"Travel companions":"Who carries it when its weight becomes inconvenient, and what goes unsaid?",
"Collaborators":"Whose contribution is visible in the finished object, and whose has disappeared?",
"Host & guest":"When does being invited to use it begin to feel like belonging?"};
const arcs=[
['A practical kindness','One person notices a small difficulty and offers the object without ceremony.','Later, the recipient reaches for it before asking anyone for help.','They offer it to someone else, repeating—or correcting—the original kindness.','Care becomes a learned action.','Let the first use solve a real problem before it carries symbolism.'],
['The unfinished loan','Someone lends it with a casual “bring it back.”','An opportunity to return it comes and goes; keeping it extends the connection.','Returning it can close the relationship, or finally make room for a chosen reunion.','An obligation becomes an excuse to stay connected.','Repeat the return question with a different answer.'],
['Unequal meaning','The giver treats it as disposable; the recipient keeps it carefully.','The giver discovers how much has been invested in that small gesture.','They must decide whether to acknowledge that meaning or withdraw from it.','Gratitude and expectation diverge.','Show different handling: tossed onto a table versus wrapped before travel.'],
['Repair as an answer','It is damaged during a disagreement or separation.','One character repairs it without asking whether the other still wants it.','The other uses it, rejects it, or alters the repair.','Mending may offer care, or presume forgiveness.','Leave a visible seam; repair needn’t erase what happened.'],
['The inherited habit','It arrives with a rule about how its previous owner used it.','The new keeper follows the rule even when it is inconvenient.','They change the use while preserving something of the person.','Loyalty becomes permission to grow.','Give the old habit a specific bodily action.'],
['A claim disguised as a gift','The giver insists that accepting it means belonging to them.','The recipient must display it to keep the giver satisfied.','Keeping, returning, or repurposing it becomes a choice about autonomy.','Affection turns into ownership.','Let the terms of the gift emerge in behavior.'],
['The false provenance','A cherished story explains where it came from.','A physical detail contradicts that story.','Its keeper chooses whether its lived meaning survives the lie.','Origin and earned meaning separate.','Plant the contradictory detail before explaining it.'],
['Recognition without a face','A distinctive handling habit is established when both people are together.','The object surfaces elsewhere, bearing evidence of the same habit.','Someone recognizes the person through the gesture or trace.','A small habit carries identity across absence.','Make the identifying trace plausible and specific.'],
['Refused, then accepted','An offer is rejected because accepting help feels costly.','The same need returns when the giver is absent or unavailable.','Accepting the object now acknowledges something the character once denied.','Pride shifts toward trust.','Reuse the original gesture with a changed response.'],
['A substitute that fails','One person replaces the lost object with something finer.','The replacement lacks the mark or inconvenience that mattered.','They learn what cannot be purchased—or create a new shared history.','Value separates from price.','Make the missing imperfection carry a remembered action.'],
['A shared custody','Two people agree to exchange it at a regular interval.','One exchange is missed, delayed, or carried out by a third person.','The next handoff reveals whether the ritual still binds them.','Routine becomes a measure of commitment.','Vary one element of a familiar exchange.'],
['Released on purpose','Someone protects it long after its practical use has ended.','Keeping it begins to obstruct a present need or relationship.','They give it away, use it up, or let it change.','Letting go can complete an attachment.','Make release a visible action, without requiring an explanatory speech.'],
["The private language", "Two people give the object a name that makes sense only to them.", "One uses that name in front of someone who does not know its history.", "They explain it together, keep it private, or allow a new person into the joke.", "Shared language becomes a boundary they can move.", "Let the nickname arise from a specific mishap."],
["Care returned", "One person always prepares or carries it for the other.", "Their circumstances change, and the usual caretaker cannot perform the task.", "The other takes over, adjusting the ritual to suit the person who began it.", "Dependence makes room for reciprocity.", "Repeat a familiar action with the hands reversed."],
["A place at the table", "The object is set aside for a regular visitor.", "Someone puts it away after a long absence.", "Its return to use marks a welcome, or makes room for a different guest.", "Hospitality gives absence a visible shape.", "Establish where it belongs before leaving that place empty."],
["Credit left off", "Two people make or adapt the object together.", "Only one is praised for the finished work.", "The credited person names the hidden contribution, or the other makes their own mark.", "A shared achievement tests fairness.", "Give each contribution a distinguishable physical trace."],
["An agreed boundary", "Two people agree that the object will stay in a particular place.", "One moves it for a reason they consider harmless.", "They restore the agreement or negotiate a new one with its cost understood.", "Respect depends on taking a small limit seriously.", "Show the empty space before the argument about it."],
["The difficult handoff", "Someone asks an intermediary to deliver it to a person they avoid.", "The intermediary learns why a simple delivery has become difficult.", "The object arrives with the intended message, a changed one, or no message at all.", "Avoided contact still asks something of another person.", "Let the messenger decide one concrete detail of the delivery."],
["A lesson reversed", "An experienced person demonstrates how to use it.", "A new situation defeats their familiar method.", "The learner finds another way and invites the teacher to try.", "Authority becomes mutual curiosity.", "Repeat the first demonstration with the roles exchanged."],
["The wrong recipient", "The object reaches someone other than its intended recipient.", "Its new keeper uses it in a way the sender never imagined.", "Returning it requires acknowledging the life it has acquired elsewhere.", "An error creates a connection nobody planned.", "Make the mistaken handoff ordinary and believable."],
["Permission to disagree", "The object stands for an activity two people are expected to share.", "One admits they have never enjoyed that activity.", "They find a different use for it or allow separate pleasures without ending the bond.", "Closeness survives a difference once hidden.", "Show the effort of pretending before the admission."],
["A small act of witness", "One person keeps the object after seeing an overlooked kindness.", "The person who acted kindly believes nobody remembers.", "The keeper brings it out when recognition can matter, without demanding a reward.", "Attention gives an ordinary action lasting weight.", "Choose a trace that records the act without explaining it."],
["A ritual interrupted", "Two people use it to mark an ordinary recurring occasion.", "A change in their lives makes the old ritual impossible.", "They invent a smaller or different ritual using what remains available.", "Continuity comes from adapting together.", "Preserve one sensory detail while changing the setting."],
["The shared mistake", "Both people damage or misuse it and agree to conceal what happened.", "Their explanations drift apart when someone asks about the damage.", "They admit their parts together or let one person bear the blame.", "Complicity becomes a test of responsibility.", "Give each account one detail the other could not have noticed."]
];
const details=['A hidden mark only one person would recognize.','Wear that reveals how it was held, carried, or used.','A repair made with materials the owner would never choose.','A smell that belongs to its former surroundings.','A missing part that the keeper refuses to replace.','A stain with an innocent explanation and a private one.','A date that means something different to each person.','An awkward size or weight that makes keeping it inconvenient.','A concealed message that was never meant to be found.','A small sound that announces its presence before it is seen.','A mistaken name that nobody has corrected.','A change in texture that can be noticed in darkness.',
"A carrying pouch made from something that once belonged to someone else.",
"A polished spot where two different hands habitually meet.",
"A label written for someone who needed larger letters.",
"A deliberate alteration that makes it fit only one particular place.",
"A price still visible beneath the wrapping of a carefully presented gift.",
"A small repair signed with an initial instead of a name.",
"A knot tied by someone who could never learn the usual method.",
"A color chosen to help its owner find it among other belongings.",
"A second set of instructions added after the first set failed.",
"A trace of packing material from a journey nobody discusses.",
"A worn edge that matches the shelf where it used to rest.",
"A protective cover that conceals the feature its maker liked best."];
const turns=['The person who gave it denies remembering the gift.','Someone repairs the feature its keeper valued most.','A stranger recognizes it for an entirely different reason.','The keeper discovers a second, apparently identical object.','It turns up in the possession of someone considered an enemy.','Someone uses it for its ordinary purpose during a solemn moment.','The person who wanted it finally has a chance to refuse it.','Its usefulness matters more than its history for one urgent scene.','A child invents a new meaning for it.','The story attached to it is true, but belongs to a different person.','It survives the relationship and enters another.','The keeper realizes they have forgotten one detail they thought permanent.',
"The intended recipient asks for it to be given to someone else.",
"Two people arrive with equally convincing claims to have made it.",
"An old instruction turns out to have been a preference rather than a necessity.",
"The object is needed in two places at the same time.",
"Someone remembers the exchange clearly but disputes who was being generous.",
"The keeper must ask an estranged person how to care for it.",
"Its familiar sound interrupts a conversation at exactly the wrong moment.",
"The person expected to inherit it does not want it.",
"A repair reveals a message hidden by an earlier repair.",
"Someone recognizes their own uncredited work in it.",
"The keeper lends it out and discovers how difficult waiting can be.",
"Using it as intended will erase a mark someone wants to preserve."];
